<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <!-- Ruta por defecto si no le pasas el parámetro en la consola -->
    <VintagestoryDir Condition="'$(VintagestoryDir)' == ''">C:\Users\telle\AppData\Roaming\Vintagestory</VintagestoryDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="VintagestoryAPI">
      <HintPath>$(VintagestoryDir)\VintagestoryAPI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VSSurvivalMod">
      <HintPath>$(VintagestoryDir)\Mods\VSSurvivalMod.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(VintagestoryDir)\Lib\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>